---
hostname: jira-db

postgresql_user: postgres
postgresql_version: 9.6
postgresql_version_raw: "{{ postgresql_version|string }}"
postgresql_homedir: "/var/lib/pgsql"
postgresql_basedir: "{{ postgresql_homedir }}/{{ postgresql_version_raw }}"
postgresql_datadir: "{{ postgresql_basedir }}/data"
pgbackrest_user: pgbackrest

postgresql_databases:
  - { db: "jiradb_rus", owner: "jiraffuser", encoding: "UNICODE", lc_collate: "C", lc_ctype: "C", template: "template0" }

postgresql_reload_direct: yes

postgresql_extensions:
  - { ext: "pg_stat_statements", db: "jiradb_rus"}

sysctl_conf:
  - { name: "vm.nr_hugepages", value: "1120" }
  - { name: "vm.overcommit_memory", value: "2" }

pg_stat_statements:
  track: all

disable_thp: true

postgresql_conf:
  checkpoint_completion_target: 0.9
  huge_pages: on
  shared_preload_libraries:
    - pg_stat_statements


postgresql_additional_packages:
  - nfs-utils
  - pgbackrest

node_exporter: true
postgresql_exporter: true
logrotate: true
firewall: true
postgresql_wal_backup_enable: true
wal_archive_command: pgbackrest --stanza=jira-db archive-push %p

# logrotation
logrotate_applications:
  - name: postgresql
    definitions:
      - logs:
          - "{{ postgresql_datadir }}/pg_log/*.log"
        options:
          - daily
          - rotate 7
          - copytruncate
          - compress
          - delaycompress
          - notifempty
          - missingok
          - su root root
...
