---
hostname: jira
jira_user: jira
jira_app_directory: /opt/atlassian/jira
jira_home_directory: /var/atlassian/application-data/jira
node_exporter: true
logrotate: true
firewall: true

# nginx settings

nginx_site_directories:
  - /etc/nginx/ssl/jira
  - /etc/nginx/sites-available
  - /etc/nginx/sites-enabled
  - "/var/log/nginx/{{ confl_fqdn }}"
  - "/var/log/nginx/{{ fqdn }}"
  - "/var/log/nginx/{{ additional_fqdn }}"

nginx_modified_files:
  - { src: nginx/nginx.conf.j2, dest: /etc/nginx/nginx.conf }
  - { src: nginx/jira.j2, dest: /etc/nginx/sites-available/jira }
  - { src: nginx/sd.j2, dest: /etc/nginx/sites-available/sd }
  - { src: nginx/jira.crt, dest: /etc/nginx/ssl/jira/jira.crt }
  - { src: nginx/jira.key, dest: /etc/nginx/ssl/jira/jira.key }
  - { src: nginx/dhparam.pem, dest: /etc/nginx/ssl/dhparam.pem }

nginx_enabled_sites:
  - { src: /etc/nginx/sites-available/jira, dest: /etc/nginx/sites-enabled/jira }
  - { src: /etc/nginx/sites-available/sd, dest: /etc/nginx/sites-enabled/sd }

# logrotate
logrotate_applications:
  - name: nginx
    definitions:
      - logs:
          - /var/log/nginx/*.log
          - /var/log/nginx/{{ confl_fqdn }}/*.log
          - /var/log/nginx/{{ fqdn }}/*.log
          - /var/log/nginx/{{ additional_fqdn }}/*.log
        options:
          - daily
          - delaycompress
          - size 4096k
          - maxage 31
          - rotate 7
          - missingok
          - nocreate
          - sharedscripts
          - postrotate test ! -f /var/run/nginx.pid || kill -USR1 `cat /var/run/nginx.pid`
          - endscript

# borg
borg_version: 1.1.9

# jira settings
jdbc_version: 42.2.8
jvm_minimum_memory: 6144
jvm_maximum_memory: 6144
jira_version: 8.5.8
jira_modified_files:
  - { src: "jira/velocity.properties", dest: "{{ jira_app_directory }}/atlassian-jira/WEB-INF/classes/" }
  - { src: "jira/ProductGroup.vm", dest: "{{ jira_app_directory }}/atlassian-jira/WEB-INF/classes/templates/email/html/includes/fields/" }
  - { src: "jira/header.vm", dest: "{{ jira_app_directory }}/atlassian-jira/WEB-INF/classes/templates/email/html/includes/" }
  - { src: "jira/summary-bottom.vm", dest: "{{ jira_app_directory }}/atlassian-jira/WEB-INF/classes/templates/email/html/includes/" }
  - { src: "jira/footer.vm", dest: "{{ jira_app_directory }}/atlassian-jira/WEB-INF/classes/templates/email/html/includes/" }
  - { src: "jira/issuecreated.vm", dest: "{{ jira_app_directory }}/atlassian-jira/WEB-INF/classes/templates/email/html/" }
  - { src: "jira/server.xml.j2", dest: "{{ jira_app_directory }}/conf/server.xml" }
  - { src: "jira/setenv.sh.j2", dest: "{{ jira_app_directory }}/bin/setenv.sh" }
  - { src: "jira/set-gc-params.sh.j2", dest: "{{ jira_app_directory }}/bin/set-gc-params.sh" }
  - { src: "jira/check-java.sh.j2", dest: "{{ jira_app_directory }}/bin/check-java.sh" }
  - { src: "jira/jira-application.properties.j2", dest: "{{ jira_app_directory }}/atlassian-jira/WEB-INF/classes/jira-application.properties" }
  - { src: "jira/jira-config.properties.j2", dest: "{{ jira_home_directory }}/jira-config.properties" }


jira_additional_packages:
  - fontconfig
  - nfs-utils
...
