---
- name: Make .ssh dir
  ansible.builtin.file:
    path: /root/.ssh
    state: directory
    owner: root
    group: root
    mode: 0600

- name: Add ssh private keys to the host
  template:
    src: id_rsa
    dest: /root/.ssh/id_rsa

- name: Add ssh public keys to the host
  template:
    src: id_rsa.pub.j2
    dest: /root/.ssh/id_rsa.pub

- name: Add ssh authorized keys to the host
  template:
    src: authorized_keys.j2
    dest: /root/.ssh/authorized_keys

- name: Add webserver to known_hosts
  known_hosts:
    name: webserver
    key: webserver,10.100.100.100 {{ ssh_cluster_pub_key }}  # some key gibberish
    path: /root/.ssh/known_hosts
    state: present

- name: Add databse to known_hosts
  known_hosts:
    name: databse
    key: databse,10.100.100.101 {{ ssh_cluster_pub_key }}  # some key gibberish
    path: /root/.ssh/known_hosts
    state: present

- name: Add zabbix to known_hosts
  known_hosts:
    name: zabbix
    key: zabbix,10.100.100.102 {{ ssh_cluster_pub_key }}  # some key gibberish
    path: /root/.ssh/known_hosts
    state: present

- name: Add backup to known_hosts
  known_hosts:
    name: backup
    key: backup,10.100.100.103 {{ ssh_cluster_pub_key }}  # some key gibberish
    path: /root/.ssh/known_hosts
    state: present

- name: Restart sshd
  systemd:
    name: sshd
    state: restarted
...