---
- name: Make .ssh dir
  ansible.builtin.file:
    path: /root/.ssh
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=r,o=r

- name: Add ssh private keys to the host
  template:
    src: id_rsa
    dest: /root/.ssh/id_rsa

- name: Add ssh public keys to the host
  template:
    src: id_rsa.pub.j2
    dest: /root/.ssh/id_rsa.pub

- name: Add ssh authorized keys to the host
  template:
    src: authorized_keys.j2
    dest: /root/.ssh/authorized_keys

- name: Add ssh known hosts to the host
  template:
    src: known_hosts
    dest: /root/.ssh/known_hosts

- name: Restart sshd
  systemd:
    name: sshd
    state: restarted
...