- name: Apply zabbix-agentd config
  template:
    src: zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
 
- name: Start and enable zabbix-agentd
  systemd:
    name: zabbix-agent
    state: started
    enabled: yes
