- name: Enable Zabbix yum repository
  template:
    src: ../templates/zabbix.repo.j2
    dest: /etc/yum.repos.d/zabbix.repo
 
- name: Install zabbix-server and zabbix-agent
  yum:
    name:
      - zabbix-agent
