---
- name: Drop PostgreSQL databases if exist
  become_user: "{{ postgresql_user }}"
  postgresql_db:
    name: "{{ item.db }}"
    state: absent
  loop: "{{ postgresql_databases | flatten(1) }}"
  when: postgresql_databases|length > 0 and postgresql_drop_databases is defined and postgresql_drop_databases == true

# - name: PostgreSQL databases
#   become_user: "{{ postgresql_user }}"
#   postgresql_db:
#     name: "{{ item.db }}"
#     owner: "{{ item.owner }}"
#     encoding: "{{ item.encoding }}"
#     lc_collate: "{{ item.lc_collate }}"
#     lc_ctype: "{{ item.lc_ctype }}"
#     template: "{{ item.template }}"
#     state: present
#   loop: "{{ postgresql_databases | flatten(1) }}"
#   when: postgresql_databases|length > 0
