---
- name: PostgreSQL users
  become_user: "{{ postgresql_user }}"
  postgresql_user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    encrypted: "yes"
    state: present
  ignore_errors: yes
  loop: "{{ postgresql_users | flatten(1) }}"
  when: postgresql_users|length > 0
...
