---
- name: install epel-release
  yum:
    name:
      - epel-release

- name: install zabbix-server
  include_tasks: zabbix_server_install.yml

- name: configure zabbix-server
  include_tasks: zabbix_server_configure.yml
