- name: Save pgpass for access remote db
  template:
    src: ../templates/pgpass.j2
    dest: /root/.pgpass
    mode: 0600

- name: Setup PostgreSQL Database
  shell: |
    psql -U postgres -w -p 5432 -h 10.100.100.101 -c "CREATE USER zabbix WITH PASSWORD 'zabbix';"
    psql -U postgres -w -p 5432 -h 10.100.100.101 -c "CREATE DATABASE zabbix WITH OWNER zabbix;"
    zcat /usr/share/doc/zabbix-server-pgsql*/create.sql.gz | psql -U zabbix -w -p 5432 -h 10.100.100.101 zabbix

- name: Apply nginx config for zabbix
  template:
    src: ../templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: Apply php-ini config
  template:
    src: ../templates/php.ini.j2
    dest: /etc/php.ini

- name: Apply php-fpm config
  template:
    src: ../templates/php-fpm.conf.j2
    dest: /etc/php-fpm.conf

- name: Apply php-fpm www config
  template:
    src: ../templates/php-fpm.www.conf.j2
    dest: /etc/php-fpm.d/www.conf

- name: Apply zabbix-server config
  template:
    src: ../templates/zabbix_server.conf.j2
    dest: /etc/zabbix/zabbix_server.conf

- name: Apply zabbix-web php config
  template:
    src: ../templates/zabbix.conf.php.j2
    dest: /etc/zabbix/web/zabbix.conf.php

- name: Disable SeLinux
  shell: setenforce 0 && sleep 3

- name: Start and enable zabbix-server
  systemd:
    name: zabbix-server
    state: started
    enabled: yes

- name: Start and enable php-fpm
  systemd:
    name: php-fpm
    state: started
    enabled: yes

- name: Restart and enable nginx
  systemd:
    name: nginx
    state: restarted
    enabled: yes
