- name: Setup PostgreSQL Database
  shell: |
    sudo -iu postgres createuser -E zabbix
    sudo -iu postgres psql -c "ALTER USER zabbix WITH PASSWORD 'zabbix';"
    sudo -iu postgres createdb -O zabbix zabbix
    zcat /usr/share/doc/zabbix-server-pgsql*/create.sql.gz | sudo -u zabbix psql zabbix

- name: Apply nginx config for zabbix
  template:
    src: ../templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: Apply php config
  tasks:
    - template:
        src: ../templates/php.ini.j2
        dest: /etc/php.ini
    - template:
        src: ../templates/php-fpm.conf.j2
        dest: /etc/php-fpm.conf
    - template:
        src: ../templates/php-fpm.www.conf.j2
        dest: /etc/php-fpm.d/www.conf'

- name: Apply zabbix-server config
  template:
    src: ../templates/zabbix_server.conf.j2
    dest: /etc/zabbix/zabbix_server.conf

- name: Disable SeLinux
  shell: setenforce 0 && sleep 3

- name: Start and enable zabbix-server
  systemd:
    name: zabbix-server
    state: started
    enabled: yes

- name: Start and enable php-fpm
  systemd:
    name: php-fpm
    state: started
    enabled: yes

- name: Restart and enable nginx
  systemd:
    name: nginx
    state: restarted
    enabled: yes
