- name: Setup PostgreSQL Database
  shell: sudo -iu postgres createuser -E zabbix
  shell: sudo -iu postgres psql -c "ALTER USER zabbix WITH PASSWORD 'zabbix';"
  shell: sudo -iu postgres createdb -O zabbix zabbix
  shell: zcat /usr/share/doc/zabbix-server-pgsql*/create.sql.gz | sudo -u zabbix psql zabbix

- name: Setup zabbix-server
  template:
    src: ../templates/zabbix_server.conf.j2
    dest: /etc/zabbix/zabbix_server.conf

- name: Setup nginx
  template:
    src: ../templates/zabbix_nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  systemd:
    name: nginx
    state: restarted
    enabled: yes
