- name: Setup PostgreSQL Database
  shell: |
    sudo -iu postgres createuser -E zabbix
    sudo -iu postgres psql -c "ALTER USER zabbix WITH PASSWORD 'zabbix';"
    sudo -iu postgres createdb -O zabbix zabbix
    zcat /usr/share/doc/zabbix-server-pgsql*/create.sql.gz | sudo -u zabbix psql zabbix

- name: Apply nginx config for zabbix
  template:
    src: ../templates/zabbix_nginx.conf.j2
    dest: /etc/opt/rh/rh-nginx116/nginx/conf.d/zabbix.conf

- name: Apply php-fpm config
  template:
    src: ../templates/zabbix_php-fpm.conf.j2
    dest: /etc/opt/rh/rh-php72/php-fpm.d/zabbix.conf

- name: Apply zabbix-server config
  template:
    src: ../templates/zabbix_server.conf.j2
    dest: /etc/zabbix/zabbix_server.conf

- name: Disable SeLinux
  shell: setenforce 0

- name: Start and enable zabbix-server
  systemd:
    name: zabbix-server
    state: started
    enabled: yes

- name: Start and enable php-fpm
  systemd:
    name: rh-php72-php-fpm
    state: started
    enabled: yes

- name: Start and enable nginx
  systemd:
    name: nginx
    state: started
    enabled: yes
