# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :pamauth => {
        :box_name => "centos/7",
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vbguest.auto_update = false
          box.vm.host_name = boxname.to_s

          box.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "200"]
          end
          
          box.vm.provision "shell", inline: <<-SHELL
            useradd -m test-user
            echo 'test-user:123'|chpasswd
            useradd -m test-admin
            echo 'test-admin:123'|chpasswd
            useradd -m test-docker
            echo 'test-docker:123'|chpasswd
            groupadd admin
            usermod -aG admin test-admin
            sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
            systemctl restart sshd
            echo '*;*;*;Wd' > /etc/security/time.conf
            echo -e 'admin\nvagrant' > /etc/login.group.allowed
            cat /vagrant/pam-sshd > /etc/pam.d/sshd
          SHELL

      end
  end
end
