# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :nginx => {
        :box_name => "centos/7",
        :ip_addr => '10.100.100.100'
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.synced_folder ".", "/vagrant", disabled: false
      config.vm.network "forwarded_port", guest: 80, host: 8080
      config.vm.network "forwarded_port", guest: 12345, host: 12345
      config.vm.network "forwarded_port", guest: 23456, host: 23456
      config.vm.network "forwarded_port", guest: 34567, host: 34567
      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vbguest.auto_update = false
          box.vm.host_name = boxname.to_s

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "200"]
          end

          box.vm.provision "ansible" do |ansible|
            ansible.playbook = "nginx.yml"
          end

          box.vm.provision "shell", inline: <<-SHELL
            yum -y install policycoreutils-python policycoreutils-devel
            ln -s /usr/sbin/nginx /usr/sbin/nginx_custom
            ln -s /etc/nginx /etc/nginx_custom
            ln -s /var/log/nginx /var/log/nginx_custom
            ln -s /usr/share/nginx /usr/share/nginx_custom
            mkdir /var/tmp/nginx_custom
            cp /vagrant/nginx_custom* /var/tmp/nginx_custom
            cd /var/tmp/nginx_custom
            make -f /usr/share/selinux/devel/Makefile
            semodule -i nginx_custom.pp
            semodule -e nginx_custom
            semanage port -a -t binkp_port_t -p tcp 34567
          SHELL

      end
  end
end
