---
- name: Install filebeat
  yum:
    name: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-{{ filebeat_version }}-x86_64.rpm
    state: present

- name: Apply config
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml

- name: Start and enable filebeat service
  systemd:
    name: filebeat
    state: restarted
    enabled: yes
...