version: "3.7"
services:
  php:
    build:
      context: ./
      dockerfile: php.Dockerfile
    image: oliferuk/php-otus
    volumes:
      - ./data/index.php:/var/www/php/index.php
    networks:
      otus:
  nginx:
    build:
      context: ./
      dockerfile: nginx.Dockerfile
    image: oliferuk/nginx-otus
    depends_on: 
        - php
    volumes:
      - ./data/index.php:/var/www/php/index.php
    ports:
        - 80:80
    networks:
      otus:

networks:
  otus:

