---
- name: create a JIRA user
  user:
    name: "{{ jira_user }}"
    state: present

- name: Install additional packages
  yum:
    name: "{{ jira_additional_packages }}"
  when: jira_additional_packages|length > 0
  tags: [ packages ]

- name: create JIRA app and home directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ jira_user }}"
    group: "{{ jira_user }}"
  loop:
    - "{{ jira_app_directory }}"
    - "{{ jira_home_directory }}"

- name: download and unarchive JIRA
  unarchive:
    src: "https://product-downloads.atlassian.com/software/jira/downloads/atlassian-jira-software-{{ jira_version }}.tar.gz"
    dest: "{{ jira_app_directory }}"
    owner: "{{ jira_user }}"
    group: "{{ jira_user }}"
    extra_opts: [--strip-components=1]
    remote_src: true
  when: not ansible_check_mode

- name: update configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ jira_user }}"
    group: "{{ jira_user }}"
    backup: yes
  loop: "{{ jira_modified_files }}"
  when:
    - jira_modified_files is defined
    - not ansible_check_mode
  tags:
    - jira_configuration

- name: Apply nginx configuration
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  loop:
    - { src: 'nginx.conf.j2', dest: '/etc/nginx/nginx.conf' }
    - { src: 'jira.nginx.site.j2', dest: '/etc/nginx/conf.d/default.conf'}

- name: setup running JIRA as service
  template:
    src: jira.service.j2
    dest: /lib/systemd/system/jira.service
  notify: reload systemd

- block:
  - name: find postgresql jdbc drivers
    find:
      path: "{{ jira_app_directory }}/lib/"
      pattern: postgresql-*
    register: postgresql_drivers

  - name: delete postgresql jdbc drivers
    file:
      path: "{{ item.path }}"
      state: absent
    loop: "{{ postgresql_drivers.files }}"

  - name: download postgresql jdbc driver
    get_url:
      url: "https://jdbc.postgresql.org/download/postgresql-{{ jdbc_version }}.jar"
      dest: "{{ jira_app_directory }}/lib/"
      owner: "{{ jira_user }}"
      group: "{{ jira_user }}"
  when:
    - jdbc_version is defined
    - not ansible_check_mode
  tags:
    - jdbc_driver_configuration
...
