---
- hosts: backup
  become: true
  roles:
    - pgbackrest
    - role: borgbackup
      borg_repository: /var/backups/jira/home
      borg_source_directories:
        - /var/atlassian/application-data/jira
      borg_retention_policy:
        keep_hourly: 3
        keep_daily: 7
        keep_weekly: 4
        keep_monthly: 6
    - zabbix-agent
    - ssh-keychange

  tasks:
    - name: Init borg repo
      shell: borg init --encryption=none /var/backups/jira/home
      environment:
        BORG_UNKNOWN_UNENCRYPTED_REPO_ACCESS_IS_OK: yes
      ignore_errors: True