---
- hosts: database
  become: true
  roles:
    - filebeat
    - postgresql
    - pgbackrest
    - zabbix-agent
    - ssh-keychange
  tasks:
    - name: Open 5432 port for default zone
        ansible.posix.firewalld:
          port: 5432/tcp
          permanent: yes
          state: enabled