# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :webserver => {
        :box_name => "centos/7",
        :ip_addr => '10.100.100.100'
  },
  :database => {
        :box_name => "centos/7",
        :ip_addr => '10.100.100.101'
  },
  :zabbix => {
        :box_name => "centos/7",
        :ip_addr => '10.100.100.102'
  },
  # :backup => {
  #       :box_name => "centos/7",
  #       :ip_addr => '10.100.100.103'
  # }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          # Disable Gueast Additions install
          box.vbguest.auto_update = false
          # Disable syncing of ./ directory
          box.vm.synced_folder ".", disabled: true
          box.vm.host_name = boxname.to_s

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "200"]
          end
          
          box.vm.provision "shell", inline: <<-SHELL
            localedef -i ru_RU -f UTF-8 ru_RU.UTF-8
            mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh
            sed -i '65s/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
            systemctl restart sshd
          SHELL

      end

  end

  config.vm.define "webserver" do |webserver|
    # webserver.vm.network "forwarded_port", guest: 80, host: 8080
    webserver.vm.provision "ansible" do |ansible|
      ansible.playbook = "webserver.yml"
    end
  end

  config.vm.define "database" do |database|
    # database.vm.network "forwarded_port", guest: 5432, host: 5432
    database.vm.provision "ansible" do |ansible|
      ansible.playbook = "database.yml"
    end
  end

  config.vm.define "zabbix" do |zabbix|
    zabbix.vm.network "forwarded_port", guest: 80, host: 8080
    zabbix.vm.provision "ansible" do |ansible|
      ansible.playbook = "zabbix.yml"
    end
  end

  # config.vm.define "backup" do |backup|
  #   backup.vm.provision "ansible" do |ansible|
  #     ansible.playbook = "backup.yml"
  #   end
  # end
end
