---
- hosts: webserver
  become: true
  roles:
    - nginx
    - java
    - postgresql-client
    - jira
    - zabbix-agent
    - role: borgbackup
      borg_repository: vagrant@backup:/var/backups/jira/home
      borg_source_directories:
        - /var/atlassian/application-data/jira
      borg_retention_policy:
        keep_hourly: 3
        keep_daily: 7
        keep_weekly: 4
        keep_monthly: 6
    - ssh-keychange
    # - jira-restore