---
- name: reload systemd
  systemd:
    daemon_reload: yes

- name: Stop and disable nginx
  systemd:
    name: nginx
    state: stopped
    enabled: no

- name: Start and enable jira
  systemd:
    name: jira
    state: started
    enabled: yes